workflows:
  - name: code-cpu
    help: "Runs a VS Code IDE"
    provider: code
    setup:
      - pip install -r dev-environments/requirements.txt

  - name: lab-cpu
    help: "Runs a JupyterLab application"
    provider: lab
    setup:
      - pip install -r dev-environments/requirements.txt

  - name: notebook-cpu
    help: "Runs a Jupyter notebook application"
    provider: lab
    setup:
      - pip install -r dev-environments/requirements.txt

  - name: code-gpu
    help: "Runs a VS environment Code with GPU"
    provider: code
    setup:
      - pip install -r dev-environments/requirements.txt
    resources:
      gpu:
        count: 1

  - name: ssh
    help: "Runs a VM with SSH enabled"
    provider: bash
    ssh: true
    commands:
      - tail -f /dev/null

  - name: code-v100-spot
    help: "Runs a VS Code IDE with 8 V100 NVIDIA Tesla GPUs using spot instances"
    provider: code
    resources:
      gpu:
        name: V100
        count: 8
      interruptible: true

  - name: code-conda
    help: "Runs a VS Code IDE with the 'myenv' Conda environment"
    provider: code
    python: 3.11
    setup:
      - conda env create -f dev-environments/environment.yaml

  - name: code-cached
    help: "Runs a VS Code IDE with cached folders"
    provider: code
    cache:
      - path: ~/.cache/pip
      - path: ./data
      - path: ./models